### ISSUE TITLE
Nazwiska z RRB

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#10]
Przymierzam się do dopisania wczytywania nazwisk z RRB.

Pytania:

1. Integrować w jakikolwiek sposób z istniejącym interfejsem nazwisk z Par/Teamów?  
Mówię tu o zachowaniu opcji "Synchronizuj teraz", "Wymuś przesłanie wszystkich" i "Synchronizuj cyklicznie". To by wymagało pewnie wprowadzenia jakiejś warstwy abstrakcji dla listy spisu nazwisk, żeby logika prawej części panelu pozostała bez zmian, a jedynie w lewej części panelu wczytywać informacje z .rrt zamiast MySQLa.

2. RRB oczywiście nie trzyma osobno imienia i nazwiska zawodnika. To sprawia, że trzeba zgadywać przy skracaniu imienia do inicjału.  
W CEZaRze są trzy pozycje zawierające spację w nazwisku (tj. więcej niż jedno słowo w nazwisku) oraz nikogo, kto by miał spację w imieniu - strzelam, że dlatego, że drugie imiona są trzymane osobno i nie wystawiane w CSVce. Narzuca się więc traktowanie ciągu do pierwszej spacji jako imienia, a całej reszty jako nazwiska.  
Spotkaliście się kiedyś z jakimś przypadkiem upartego uczestnika, który upierałby się przy wyświetlaniu go w wynikach jako "Anna Maria", "Jan Maria", "Jan Paweł", czy cokolwiek?  
Przy okazji patrzenia w nietypowe nazwiska, okazało się, że przydałoby się również podmienić poczciwą metodę bezOgonkow na coś, co nie będzie sprawiać problemów przy okazji różnych Jørgensenów.

**Comment by emkael** [comment]
Wydłubałem tyle: https://github.com/emkael/aktywator/tree/rrb-names

Gałąź jest mocno eksperymentalna, podbiłem numer wersji do 1.1.0-beta i chcę się na razie wstrzymać ze scaleniem do głównej gałęzi, przynajmniej do czasu zmobilizowania jakichś ~~jeleni~~ testerów.

Skrót tego, co się dzieje w gałęzi:
 * Trochę porządków (jakieś stałe w miejsce magicznych numerków itp.).
 * Komunikaty błędów MySQL/wczytywania nazwisk do tej pory były typu Abort/Retry/Ignore - to miało o tyle sensu, że faktycznie program oczekuje od użytkownika wyboru między Ignore a Abort. Niestety, jako że funkcjonalność Retry jest kompletnie nieobsłużona, to trzyprzyciskowe komunikaty były również nieco mylące. Jako istota z natury leniwa, zmieniłem okna komunikatów na Tak/Nie, można w sumie otworzyć jakieś zgłoszenie na dorobienie ponawiania (danego nazwiska? całej listy?).
 * Naprawiłem prawidłowe czyszczenie po sobie połączenia do MySQL i OleDB w procesie (w sumie samo się naprawiło, bo zmieniłem podejście do czytania i pisania nazwisk).
 * Rozdzieliłem i zgeneralizowałem model czytania nazwisk z różnych źródeł (Pary/Teamy, później również RRB). Dotychczasowa klasa `Tournament` zmieniła się w `MySQLTournament`, z której następnie wywaliłem wszystkie fragmenty specyficzne dla konkretnego programu - do podklas `ParyTournament` i `TeamyTournament`. W klasie `MySQLTournament` pozostała logika listowania baz MySQL i rozpoznawania, które z nich są bazami JFR.
 * Sama procedura czytania nazwisk operuje na abstrakcji - klasie `Tournament`, której podklasami są `MySQLTournament` i nowo utworzona `RRBTournament`. Lista nazwisk przekazywana jest do miejsca, w którym dotychczas nazwiska były zapisywane do BWSa w całości, na raz, jako słownik indeksowany numerami par. W efekcie - również z bazy MySQL nazwiska pobierane są na raz, jednym zapytaniem. To przy okazji ułatwiło wykrywanie braków, no i odciążyło bazę (zapytania rzędu kilkuset wierszy wyniku nie powinny stanowić problemu - a kilkaset zapytań po jednym/dwóch wierszach już mogło).
 * W końcu - dopisałem obsługę RRB-owego XMLa.
 * Do tego posprzątałem metodę normalizującą znaki diakrytyczne. Z jakiś powodów [metoda, która robi to całkiem niezawodnie](https://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net#comment48711599_2086575) (w tym: uwzględnia możliwość, że nie wszystkie znaki diakrytyczne mają w unikodzie akcenty jako odrębne modyfikatory), używa transkodowania przez Cyrylicę. Pozostaje mieć nadzieję, że obecność strony kodowej 1251 w systemach operacyjnych jest wystarczająco rozpowszechniona i nie jest czymś bardzo lokalnym.

Pytania, które fajnie byłoby wyjaśnić lub przedyskutować:

 1. Czemu przycisk do wymazywania nazwisk z BWSa jest ukryty? To jest po prostu jakaś niedokończona funkcjonalność? Czy nie wystarczy po prostu ustawić wszystkich nazwisk na pusty łańcuch i oznaczyć ich jako zaktualizowane?
 2. Umożliwiłem wczytywanie nazwisk do BWS zanim wpisane zostały numery zawodników - czyli np. gdy przed turniejem mamy gotową listę startową. Zastosowałem metodę nr 3 z dev-guide, czyli operowanie na tabeli `PlayerNumbers` zamiast wypełnianie tabeli `PlayerNames`. To oznacza, że ustawienie `BM2NameSource` musi mieć wartość `2` - ale nie spotkałem w czasie testów BWSa, który miałby ustawioną inną wartość (bo taka wartość jest ustawiana przy zapisywaniu opcji i konwersji BWSa w samym Aktywatorze). Nie jestem pewien, czy nie należałoby ustawiać jej na właściwą wartość zawsze przy wgrywaniu nazwisk, niezależnie od ufania, że ta wartość już się znajduje w BWSie.
 3. Muszę dowiedzieć się, w jaki sposób RRB ustawia pauzę - czy tylko "pauza" w polu nazwiska, czy może dodatkowo puste ID. Na razie rozpoznaję pauzę (i ustawiam w jej miejsce puste nazwisko) po zawartości nazwiska ("pauza").

**Comment by emkael** [comment]
Paczka z testową wersją, z mojego repo: https://github.com/emkael/aktywator/releases/tag/v1.1.0-beta

**Comment by emkael** [comment]
W ramach tego, co wynika z dyskusji z #9, koniecznie trzeba sprawdzić, czy pkt. 2. z pytań powyżej nie psuje czegoś w teamach.

**Comment by michzimny** [comment]
Nie przeglądałem kodu, ale z opisu (o tej dodatkowej warstwie abstrakcji) założenia wyglądają ładnie.

Nie potrafię odpowiedzieć na zadane pytania :)

Myślę, że heurystyka, że łańcuch znaków do spacji jest imieniem, jest bardzo dobra.

**Comment by emkael** [comment]
Zrobione w: https://github.com/emkael/aktywator/releases/tag/v1.1.1-beta
