### ISSUE TITLE
Numery wersji firmware i BCS dla konkretnych opcji BWS

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#11]
Zgodnie z wcześniejszym mailem, podsuwam pomysł sygnalizowania użytkownikowi minimalnej wersji pierniczków i oprogramowania dla wybranego zestawu opcji BWS.

Na razie tylko dla zakładki z checkboksami, bo ona pokrywa zdecydowaną większość (jeśli nie całość) sytuacji, w których taka informacja jest przydatna. Tzn. nie wydaje mi się, żeby jakiekolwiek opcje nazwisk/rozkładów robiły różnicę - zwykle jest tak, że szczegóły zakładek nazwisk/rozkładów degradują funkcjonalność w jakiś zdrowy sposób, a jak było coś dopisywane (np. dane analizy w widne), to "po cichu", bez angażowania w to użytkownika.

Ogólna koncepcja:
 * rozszerzyć obiekty klasy `Settings` o dwa pola typu `Version`
 * przy ustawianiu opcji (metody `save()`) emitować zdarzenie, które w razie potrzeby zaktualizuje wyświetlaną gdzieś u dołu panelu opcji informację o wymaganych wersjach
 * i tyle?

Ewentualnie można pokusić się o wyszukanie w rejestrze wersji zainstalowanego BCS i ostrzeganie, jeśli do działania wszystkich wybranych opcji wymagany jest upgrade (z firmwarem tak oczywiście nie zrobimy, ale upgrade jest często powiązany, a minimalne/maksymalne wersje potrafią być wymuszane między BCS a serwerem).

Jeśli nie masz poważnych uwag lub przeciwwskazań, spróbuję coś na dniach zaimplementować.

**Comment by michzimny** [comment]
Nie mam uwag.

**Comment by emkael** [comment]
Proponowana implementacja w #12
