### ISSUE TITLE
Lepsza kontrola, czy użytkownik ma ustawione parametry MySQLa

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#14]
Aktualnie wyznacznikiem tego, czy użytkownik wypełnił formatkę ustawień MySQL, jest niepuste hasło.

Może lepiej dołożyć do parametrów aplikacji flagę "użytkownik zapisał parametry", z domyślną wartością "nie", a przełączaną na "tak", gdy tylko użytkownik zapisze parametry, żeby program nie nagabywał użytkownika, który zapisał sobie puste hasło.

Co prawda nie testowałem nigdy, czy Aktywator działa z pustym hasłem MySQL, ale ufam, że tak.

**Comment by michzimny** [comment]
Nie widzę przeszkód, ale przy okazji wypada sprawdzić jednak, czy to puste hasło w ogóle zadziała. I z punktu widzenia Aktywatora i serwera MySQL.

**Comment by emkael** [comment]
Zrobione w: https://github.com/emkael/aktywator/releases/tag/v1.1.1-beta
