### ISSUE TITLE
Redesign checkboksów opcji BWS

### ISSUE THREAD

**Issue by Jaom** [michzimny/aktywator#16]
Zrobiło się ciasno i nieczytelnie. mkl proponował pogrupować w panele z obwódkami brzmi super

**Comment by emkael** [comment]
![zrzut ekranu 2017-08-23 00 23 11](https://user-images.githubusercontent.com/3368944/29590277-4fa9b1fa-8799-11e7-909c-ed4c83f97db2.png)

Co my na to?

**Comment by michzimny** [comment]
Like

**Comment by emkael** [comment]
To może reszta interfejsu, spójnie? :)

![zrzut ekranu 2017-08-23 14 47 14](https://user-images.githubusercontent.com/3368944/29616495-00643da8-8812-11e7-8b9e-ee859193b966.png)
![zrzut ekranu 2017-08-23 18 12 27](https://user-images.githubusercontent.com/3368944/29626338-af239d40-882e-11e7-98d0-0895c337904c.png)

**Comment by michzimny** [comment]
like

**Comment by emkael** [comment]
Zrobione w: https://github.com/emkael/aktywator/releases/tag/v1.1.1-beta

**Comment by Jaom** [comment]
1. W starej wersji layoutu dominował guzik Uruchom BMC i dobrze, bo to ważny guzik. Aktualnie jest to nie dość, że mały guzik, to jeszcze bardzo, ale to bardzo blisko X zamykającego program. Wydaje się, że dużo bardziej naturalne miejsce dla tych guzików to dół programu - zaznaczasz opcje (odruchowo lecąc od góry do dołu) i przechodzisz na sam dół, gdzie jest guzik uruchom.
2. Ja wiem, że to pierdoła, ale bardzo nie podobają mi się aktualne ikonki. ^^
3. Guzik "usuń zmiany" w zakładce Nazwiska jest niespójny wyglądem z resztą interfejsu.
4. W prawym dolnym rogu okienka nie powinno być ikonki do resize jeśli nie da się w ten sposób osiągnąć nic poza migotaniem tekstu na dole okienka (może zezwolenie na resize nie jest złe w kontekście zakładki Nazwiska, która ma potencjał wykorzystania takiej opcji).
5. Opcje rzadko używane i **niebezpieczne** (w znaczeniu robiące panikę na sali) może powinny wyglądać trochę odmiennie. Idealny przykład opcji niebezpiecznej i nieużywanej niemal nigdy to zbieranie licytacji, że nie wspomnę o rozgrywce - zaznaczenie takiej opcji przez przypadek to dramat, bo nawet naturalny flow używania pierniczka nie wywoła chyba zlikwidowania fuckupu nawet po resecie serwerka z nowymi ustawieniami (w praktyce sędzia musi odwiedzić wszystkie stoły i restować pierniki / cancelować do numeru rozdania). Zważywszy, że i tak nie wszystkie opcje są widoczne może warto wydzielić "zaawansowane i inne" i tam wrzucić opcje nigdy nieużywane (ale może ktoś się kiedyś będzie chciał pobawić) jak i niebezpieczne i rzadko używane.

**Comment by emkael** [comment]
1. Myślałem o wyrzuceniu paska z "Wczytaj ponownie" i "Zapisz do BWS" pod listę opcji, jak dawniej (może ma tam wrócić?) - ale "Uruchom BCS" zawsze był u góry. I zawsze był blisko X zamykającego program - zbliżenie go nie jest efektem redesignu, tylko efektem usunięcia zupełnie zbędnego paska górnego menu. Przeniesienie "Uruchom BCS" na dół ponownie zwiększy wysokość okna programu (bo pasek z nazwą BWSa zostaje u góry), którą i tak rozdmuchał już podział opcji. Widziałeś już wersję z kontrolkami do wyboru sektora, czy pisałeś na podstawie screenów?

2. Zapraszam do dostarczenia lepszych (optymalnie: na wolnej licencji), na razie uwaga antykonstruktywna.

3. No właśnie jest spójny. Nie może być trójwymiarowy, bo reszta przycisków jest na pasku menu, więc płaska - a usunięcie krawędzi sprawi, że przestanie wyglądać jak przycisk. Mam usunąć krawędzie?

4. Wydawało mi się, że wypychałem usunięcie chwytaka. Rozszerzalność okna wymaga ustawiania całego mnóstwa opcji doklejania krawędzi, jest do rozważenia.

5. Zapraszam do zdefiniowania listy opcji "rzadko używanych i niebezpiecznych" (hint: nigdy nie będzie obiektywna), na razie uwaga antykonstruktywna.

**Comment by Jaom** [comment]
ad 1 - ale guzik był większy, a teraz jet mały i z cała pewnością jest bliżej:
![image](https://user-images.githubusercontent.com/2835003/29710967-ea8862ca-8992-11e7-85b2-5f7471e9b76d.png)

ad 2 - dla startowania BMC proponuję ikonę BMC, która jest chyba ikonką podpierdzieloną Microsoftowi i oczywiście jest strasznie brzydka, ale za to rozpoznawalna przez usera, alternatywnie można by przerysować na glypha à la boostrap, ale to byłby chyba przerost formy nad treścią; generalnie zbiór glyphów boostrapowych wydaje się bardziej estetyczny

ad 3 - ja patrząc na niego zrozumiałem skąd się mu taki wygląd wziął, aczkolwiek spójnym bym go nie nazwał - jedno, że jest jedyny w swoim rodzaju, drugie, że pod tabelką jest "sychronizuj co", które też nie wygląda na guzik, a nim jest; być może po prostu wszystkie guziki powinny wyglądać jak guziki? Analizator 9k ma guzikowe guziki i chyba jest ok

ad 5 lista zdecydowanie nieużywanych:
- wszystkie, których nie ma aktualnie w ustawieniach (łącznie z podawaniem numeru pary jako częsci kontraktu lub wprowadzaniem liczby lew zamiast +/- czy wprowadzaniem rozkładow)

Opcje niebezpieczne z uwagi na bezpieczeństwo rozgrywek:
- pokazywanie rozkładów
- podgląd zapisów na koniec rundy automatycznie
- możliwe, że podląd zapisów bierzącej rundy
- nieskończone przewijanie wyników
- zawodnicy sami poprawiają zapisy (aczkolwiek w turnieju teamów to nie problem imho)

Opcje nieużywane zbyt często, a generujące problemy na sali:
- automatyczne wpisywanie numerów rozdań
- sprawdzanie kolejności rozdań
- zbieranie licytacji
- zbieranie rozgrywki
- sprawdź kartę wistu z rozkładem
- pokazuj znaczni brydżowe (w wariancie wyłączonym generuje pytania)
- oddzielne maksowanie sektorów (opcja zdecydowanie zaawansowana bo tylko przy sklejaniu eventów w BWSie z par)

**Comment by emkael** [comment]
1. Powiększenie rozmiaru czcionki na przycisku do 12pt i odsunięcie u góry o dalsze 10px wystarczy?  
![zrzut ekranu-1](https://user-images.githubusercontent.com/3368944/29712963-a87ac76a-899c-11e7-8979-bae664faf4e3.jpg)


2. Ikony Bootstrapa są darmowe do użycia tylko z Bootstrapem.

3. Guziki ułożone na paskach guzików wyglądają jak guziki na paskach guzików (w sensie - bardzo inaczej nie potrafią wyglądać). Żeby "wyglądały jak guziki", trzeba by je było umieścić na innej kontrolce (pasku menu) - a wtedy będziemy mieć do czynienia z dziwną hybrydą elementów 3D i płaskich.  
W skrócie: zdjąłem z przycisku "Usuń zmiany" obwódkę.

4. Roboczo wypchnąłem usunięcie chwytaka. Rozszerzanie, w tym listy nazwisk, musi chwilę poczekać.

5. Jedyne opcje, których **nie** wymieniłeś, to:
 * wszystkie opcje panelu "Rozstawienie" (dziwne, o wiele częściej widuję na turniejach kolejność rozdań niż nazwiska w pierniczkach i nigdy nikt nie narzeka)
 * pokazanie wyniku i %% wyniku
 * liczba rozdań do końca rundy i rozstawienie do kolejnej rundy
 * zbieranie wyników pośrednich i pytanie o kartę wistu
 * "automatycznie wyłącz BCS" (dziwne, wydawało mi się, że tę opcję uważasz za szkodliwą)
 * PIN, NoPlay i reset pierniczka

Nie znajduję żadnej logiki w zgrupowaniu ich razem. Powielanie podziału na "opcje Par/Teamów" i "opcje Aktywatora" mija się z celem, bo nikt Aktywatora nie używa przez przypadek.

**Comment by Jaom** [comment]
Ad 1 - nie mam zdania, wciąż mi się nie podoba, nie mam jednak propozycji lepszego rozwiązania

Ad 2 - glypicons basic set jest darmowy, można też po prostu kupić / zrzucić się nań w wersji niedarmowej, jest jeszcze font awesome

Ad 3 - nie podoba mi się, nie lubię, nie mam lepszych propozycji

Ad 5
Może powinna być opcja "pokaż opcje zaawansowane"?
Wiem, że wymieniłem sporo z opcji - większości bowiem zwykle się nie dotyka.

 "automatycznie wyłącz BCS" uważam za szkodliwe, ale jedyna poprawna opcja to resetować serwer po zakończeniu zbierania zapisów, a tego chyba nie da się dać w opcje startup? To, że ktoś ręcznie zamknie BMC będzie miało ten sam szkodliwy wpływ, więc nie widzę lepszego rozwiązania niż udokumentować ten potencjalny problem i zostawić jak jest.

**Comment by emkael** [comment]
Ad 2 - "to się weźmy i niech ktoś zrobi".

Ad 5 - Chodziło mi o to, że opcja "pokaż opcje zaawansowane" istnieje już od dawna i wygląda jak ikonka Aktywatora na pulpicie.

**Comment by Jaom** [comment]
Ad 5 - więc kolejny krok powinien być "pokaż opcje zaawansowansiejsze"?
