### ISSUE TITLE
Maksowanie sektorów

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#21]
Wersja 2.3.1 BCS (czyli dawno temu) wprowadziła dla BM2 alternatywną metodę grupowania stołów/sektorów w protokołach - pole `Group` w tabeli `Tables`.

Gdy było ono używane (a jest - bo BWSy, z którymi mam styczność, ustawiają dla wszystkich stołów `1`), opcja `GroupSections` w tabeli `Settings` była ignorowana.

Zaimplementowałem ponownie tę opcję, używając pola w `Tables` - i wygląda na działającą.  
Jedyny problem to brak możliwości przełączenia między wspólnym a oddzielnym maksowaniem sektorów w trakcie trwania sesji - nie do końca wiem, dlaczego.

Mogę jedynie się domyślać, że opcje z `Tables` nie są przeładowywane przez serwer standardowym `UpdateFromRound=997`, może konieczne jest ponowne dodanie stołów do serwera, ale nie podejmuję się proponować, jak to zrobić bezpiecznie.  
Niestety, również w "starej" wersji (`Group` w `Tables` ustawione na `0` i pisanie `GroupSections` w `Settings`), ustawienie nie jest odświeżane, albo nie umiem go skutecznie wymusić.

Może należałoby napisać do BM.

**Comment by Jaom** [comment]
Hmm, napisanie do BM sprawia wrażenie optymalnej drogi. Szczególnie, że to śmierdzi bugiem i jak go załatają kiedyś, to może coś się zepsuć po stronie aktywatora.

**Comment by emkael** [comment]
Chcesz, żebym Ci coś zredagował?

**Comment by Jaom** [comment]
Najlepiej wolałbym nie być wmieszany w komunikację,  bo to pewnie tylko ja opóźni w kontekście tego, że mam więcej rzeczy do komunikowania niż czasu by to czynić. Z niechęcią zgodzę się, że mogę być jednak dobrą osobą z uwagi na to, że z jakiegoś tajemniczego powodu chwilowo mi odpisują. Tak, poprosiłbym o zredagowanie czegoś. :(

**Comment by emkael** [comment]
Poniedziałek wieczorem/wtorek przed południem, chcę jeszcze sprawdzić cały proces na "czystym" BWSie (dotychczas testowałem poprzez usuwanie zapisów z pełnych BWSów).

**Comment by emkael** [comment]
Przy okazji okazało się, że Pary dla turniejów z jednym sektorem nie generują w tabeli `Tables` kolumny `Group` i trzeba to dopisać do konwersji BWSa.

**Comment by emkael** [comment]
>  Tak, poprosiłbym o zredagowanie czegoś. :(

Wysłałem mailem.

**Comment by emkael** [comment]
Odpowiedź od BridgeMate brzmi:

> This is a known limitation indeed.

Czy w związku z tym chcemy mieć tę funkcjonalność, ale w ograniczonej formie, czy z powrotem ją blokujemy?  
Ew. jakieś ostrzeżenie?

**Comment by Jaom** [comment]
W mojej ocenie zdecydowanie chcemy ją mieć.
Popup przed odpalaniem BMC:
"Uwaga, wybrałeś oddzielne maskowanie sektorów - tego ustawienia nie zmienisz bez recovery serwerka! [kontynuuj] [anuluj]"
Może być ok. Sądzę, że generalnie wystarczy to udokumentować, ale trwalej i skuteczniej będzie zrobić to tak, niż by z Aktywatorem zaczęła wędrować lista ograniczeń.

**Comment by emkael** [comment]
"Uwaga, wybrałeś oddzielne maskowanie sektorów" - ale to nie jest opcja tak/nie. Równie dobrze są turnieje, w których zasadne jest ostrzeganie "uwaga, wybrałeś łączne maksowanie sektorów".

Chyba, że uznajemy, że mamy ostrzegać przed czymś, co różni się od stanu obecnego.

**Comment by Jaom** [comment]
Optymalnie jest prawdopodobnie wyrzucać warning jak:
- wybrano jakieś maksowanie / pokazywanie zapisów  (nie teamy :) ) 
- BWS ma więcej jak jeden sektor

Będzie to dotyczyło małego ułamka BWSów. Nawet lepiej by wtedy ostrzegał zawsze co wybrano, bo grałem już w turniejach gdzie pierniczek pokazywał zapisy na innych rozkładach z turnieju obok...

**Comment by emkael** [comment]
> BWS ma więcej jak jeden sektor

To akurat jest łatwe, bo już teraz przy więcej niż jednym sektorze wyświetlane jest ostrzeżenie, że przy wyborze ustawień dla wszystkich sektorów ładowane są bieżące wartości dla pierwszego sektora.

Ale owszem, opcja grupowania dotyczy zarówno zapisów w protokole, jak i wyświetlanych procentów.

**Comment by emkael** [comment]
![zrzut ekranu 2017-09-12 18 41 39](https://user-images.githubusercontent.com/3368944/30338198-0f05b7ea-97eb-11e7-9509-c56972db6ddd.png)
![zrzut ekranu 2017-09-12 18 41 40](https://user-images.githubusercontent.com/3368944/30338197-0f00e65c-97eb-11e7-971a-8d5f6b262fe8.png)

Ikonka ostrzegawcza zmienia kursor na kursor z pytajnikiem.

Wystarczająco?

**Comment by Jaom** [comment]
O! Fajne 🥇
