### ISSUE TITLE
Długie nazwy BWS

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#23]
_From @emkael on November 18, 2017 8:33_

Zwijają górne menu i przyciski chowają się do podmenu.
Czasem nawet sama dłuuuuuuga nazwa się nie mieści.

_Copied from original issue: emkael/aktywator#6_

**Comment by michzimny** [comment]
Najprościej w takim przypadku może po prostu trzeba przycinać początek (środek?) ścieżki.

**Comment by emkael** [comment]
Wykombinowałem, że należy wycinać początek ścieżki po literze dysku.
Właśnie pracuję nad poprawką.
