### ISSUE TITLE
Wydajność wykrywania baz danych

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#25]
_From @emkael on November 10, 2017 8:35_

Ogarnąć.

_Copied from original issue: emkael/aktywator#4_

**Comment by emkael** [comment]
Podmieniłem `SHOW DATABASES` + iterowanie i sprawdzanie tabel `admin` na jedno zapytanie do `information_schema`.
Podobno nie jest lepiej.

Może należałoby zrezygnować z wykrywania typu bazy na tym etapie i robić to dopiero po wybraniu bazy (+ sypać błędem, jeśli baza jest nie-JFR)?

**Comment by michzimny** [comment]
Na pewno czytanie information_schema trwa tak samo długo? Podrzuciłbyś binarkę do przetestowania?

**Comment by emkael** [comment]
Testował Olo - i nie widział różnicy w szybkości listowania baz danych.
Dałem mu później do wykonania zapytanie do `information_schema`, które jest wykonywane, i wykonało się natychmiastowo. Więc albo jakiś cache metadanych serwera się z nami bawił, albo problem leży nie w warstwie komunikacji z MySQL (a już w warstwie przetwarzania danych w programie).

Problemy z `information_schema` przeważnie rozwiązuje [wyłączanie statystyk InnoDB dla metadanych](https://www.percona.com/blog/2011/12/23/solving-information_schema-slowness/), ale kto wie, co tu się dzieje.

Bieżąca binarka: https://www.dropbox.com/s/0b21zbcwbhti3ui/Aktywator.exe?dl=0

**Comment by michzimny** [comment]
Rzeczywiście, wygląda, że nadal długo. Może to po stronie aplikacji...

**Comment by emkael** [comment]
W sumie widzę jeszcze jedną oczywistą optymalizację, którą najpierw wypróbuję.
Teraz tworzone jest trochę obiektów, które wcale nie muszą być tworzone, a może w jakiś sposób ciążą.
Jeśli to nie pomoże, to nie mam pomysłu.

No i muszę poszukać jakiegoś sensownego zestawu testowego, chyba wrzucę bazy z lig centralnych z czasów generowania play-offów, było tego razem kilkadziesiąt turniejów.

**Comment by emkael** [comment]
No ba.
Pod tym samym linkiem, co wyżej, jest nowa wersja, na tyle, na ile udało mi się zauważyć różnicę, to teraz listing baz jest natychmiastowy.

**Comment by emkael** [comment]
To też w sumie można by było jeszcze potwierdzić, czy przeszło za drugą próbą poprawienia.

**Comment by emkael** [comment]
Przeszło.
