### ISSUE TITLE
Odznaczać "pokaż %% wyniku", jeśli nie jest pokazywany protokół

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#26]
Bug ponoć odwieczny.

**Comment by michzimny** [comment]
A jak na to pierniczki reagują, gdy protokół nie jest pokazywany, a "pokaż % wyniku" jest zaznaczone?

**Comment by emkael** [comment]
Nie pokazują protokołu, a pokazują %% wyniku :)

**Comment by emkael** [comment]
W sensie, %% wyniku pokazuje się na jednym ekranie wraz z zadaniem pytania, czy pokazać protokół. Jeśli nie pokazujemy protokołu, to pytanie się nie pokazuje.
