### ISSUE TITLE
Nazwiska dla indywiduela

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#30]
Grubsza Sprawa™.

Po pierwsze, odróżnianie turnieju parowego od indywidualnego może nie okazać się trywialne.

Po drugie, nie jestem pewien, czy to jest w ogóle wykonalne - w sensie, czy na poziomie BWS nazwiska nie operują numerami par, które dla turniejów indywidualnych i tak trzeba ukrywać, bo pokazują się N/E, a nie ma jak określić S/W.
Może taka funkcjonalność wymaga wręcz poważnej ingerencji w BWSa generowanego przez Pary dla indywiduelów.

**Comment by Jaom** [comment]
O ile dla turniejów indywidualnych to trudne,  o tyle dla finałów GP z indywidualnym carry-over (gdzie zawodnicy zawsze chodzą parami i mają stałą różnicę numerów, zazwyczaj 100) - coś takiego można już obsługiwać wprost, bo naokoło jest upierdliwe.

**Comment by emkael** [comment]
Pod warunkiem, że jest wykrywalne. Na razie mam wątpliwości, czy sama indywidualność turnieju jest (łatwo) wykrywalna, a co dopiero grandprixfinałowość.

**Comment by Jaom** [comment]
Z poziomu BWS to bez znaczenia, bo też mam wrażenie, że BMC obsługuje indywiduele podobnie jak teamy - z rozpędu, a nie z założenia, więc nie ma nawet feature'ów, które by były specyficzne dla indywidueli.

Z poziomu bazy danych jest trywialne, bo w  `[baza].admin.pary` jest 0 dla indi i 1 dla par.
Rozróżnienia czy to finał GP czy nie nie trzeba, bo można rozstawienie z pierwszej rudny z MySQL wczytać i tak wgrać nazwiska, a wyświetlić tylko monit "wiedz, że jeśli to zwykły indywiduel, gdzie nie chodzi się parami, to nazwiska się rozjadą, więc tego nie rób".

Nazwisk dla indywiduela chyba się nie da w ogóle ogarnąć, bo wydaje się,  że BMC musi mieć "pary" i o ile można podstępnie w Aktywatorze co rundę aktualizować "skład par", o tyle problem jest taki, że na raz często gra się dwie rundy "bieżąca, którą kończą i nowa, którą zaczynają", a nie widzę sposobu by tak oszukać BMC żeby był w stanie wyświetlać w nowej rundzie nowe pary, a w starej stare w sposób inny niż zabijanie feature'a podglądu nazwisk w trakcie rundy.

**Comment by emkael** [comment]
Incoming in v1.1.4:

![zrzut ekranu 2018-03-20 20 57 41](https://user-images.githubusercontent.com/3368944/37679519-700d5a72-2c81-11e8-8f43-e7a66fb80483.png)
![zrzut ekranu 2018-03-20 20 57 46](https://user-images.githubusercontent.com/3368944/37679563-8c75444a-2c81-11e8-9789-769d435f8467.png)
![zrzut ekranu 2018-03-20 20 57 58](https://user-images.githubusercontent.com/3368944/37679518-6ff0a33c-2c81-11e8-895a-26cd0a41f3a3.png)

**Comment by emkael** [comment]
Beta-build z nazwiskami dla indywiduela: https://github.com/emkael/aktywator/releases/tag/v1.1.4
