### ISSUE TITLE
Wyświetlanie wyniku w VP dla Teamów

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#33]
Wyświetlanie wyniku meczu w IMPach podaje zawsze wynik BEZ bieżącego (wybranego w Aktywatorze, domyślnie: pierwszego niezamkniętego) segmentu.

Wynik w VP pobierany jest z `matches` - aktualnie wyświetlana jest suma VP do wybranej w Aktywatorze rundy **włącznie**.

Jeśli chcemy wykluczyć możliwość przypadkowego ujawnienia bieżącego wyniku meczu zawodnikom (np. przez zostawienie auto-aktualizacji nazwisk do momentu, kiedy Webmaster zdąży zapisać wynik do tabeli `matches`), należałoby zmienić warunek na runda < wybranej.
Ale możemy czasem chcieć wyświetlić między segmentami meczu aktualny wynik drużyny w VP.

Która wersja jest przydatniejsza?

**Comment by michzimny** [comment]
Ta bezpieczniejsza.

09.12.2017 18:09 "Michał Klichowicz" <notifications@github.com> napisał(a):
