### ISSUE TITLE
Jakiś release przed ligą?

### ISSUE THREAD

**Issue by michzimny** [michzimny/aktywator#35]
Od ostatniego trochę commitów minęło...

**Comment by emkael** [comment]
Istotnie, minęło.

Niestety, nie udało mi się zaatakować najpoważniejszego problemu, który wypłynął od czasu wydania v1.1.2 (#32).

Wszystkie pozostałe zmiany i poprawki, którymi celowałem w v1.1.3, wydałem niedawno u siebie jako 1.1.2.9: https://github.com/emkael/aktywator/releases/tag/v1.1.2.9 - przesyłałem ją już Pawłowi Szymaszczykowi w odpowiedzi na zgłaszane przez niego błędy.

Jeśli chcemy przesunąć #32 i wydać powyższe jako 1.1.3 - nie krępuj się.

**Comment by michzimny** [comment]
Myślę, że można wydać wersję bez #32. Skompilujesz?

**Comment by emkael** [comment]
https://github.com/michzimny/aktywator/pull/36

Paczka z binarką jest podlinkowana w opisie PR. Ewentualnie, mogę sam zrobić taga i podpiąć ją do release, jak zatwierdzisz scalenie kodu do master.
