### ISSUE TITLE
Wczytywanie rozkładów niezaczynających się od N

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#38]
Rozkład zaczynający się, w notacji PBN, od innej pozycji niż N, wczytuje się obrócony.

**Comment by emkael** [comment]
Dotyczy również: emkael/bcdd#2

**Comment by michzimny** [comment]
Tam przed pierwszą ręką jest np. "N:". Zdaje się, że mój parser tę literkę ignoruje :)

**Comment by emkael** [comment]
Tak, mój parser też ignorował.

Po czym okazuje się, że Dealear4 generuje PBNy z rozkładami zaczynającym się zawsze od rozdającego :)

Wrzucę takiego PBNa od Olka, jak tylko się upewnię, że nie jest już właśnie grany.

**Comment by emkael** [comment]
https://www.dropbox.com/s/yo6wkv3u64my8tx/18bs_0204_gpp_final.pbn?dl=0
