### ISSUE TITLE
Obsługa wyniku rozdania w turnieju na IMP

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#43]
Opcje z v3 firmware'u BM2 (BM3?).

Ogarnąć, czy działają, jak działają i czy można ich użyć również w BWSach generowanych przez JFR.

Może i przez Teamy, gdybyśmy mieli taki kaprys, ale niekoniecznie - firmware obsługuje również grę meczową.

```
- IMP scoring added
- X-IMP scoring added
- Team games functionality added. Teams can review scores from both matches and view their match results in IMP at the end of the match.
```

**Comment by emkael** [comment]
![zrzut ekranu 2018-10-24 15 08 37](https://user-images.githubusercontent.com/3368944/47432555-f07ec300-d78d-11e8-87f9-e3698d5c9782.png)

Zmiany:
 * poprzesuwałem panele (zamieniłem "Rozkłady" z "Protokołem", przeniosłem wyłączanie BCS do opcji sędziowskich), żeby się zmieściło, poza tym pozmieniałem sformułowania typu "maksowanie" na jakieś uniwersalniejsze
 * opcje pokazywania wyników i grupowania sektorów są teraz niezależne od opcji pokazywania protokołu/travellera
 * wykrywam, czy BWS jest z działającego turnieju JFR Teamów
 * dla turnieju JFRT wyłączona jest opcja grupowania zapisów z sektorów - bo te pola są używane do powiązania stołów tych samych meczów, poza tym wyłączane są opcje liczenia wyników inne niż IMP (teamy)
 * dla BWSa niepochodzącego z działającego turnieju Teamów, włączane są pozostałe opcje pokazywania wyników (maksy/cav/butler), a opcja grupowania sektorów działa jak dotychczas
 * opcje wyników można ustawić niezależnie dla każdego sektora, tj. powinno dać się puścić w jednym BWSie w jednym sektorze maksy, a w drugim IMP, przy czym Aktywator nie wykrywa takiej sytuacji i np. nie wymusza w takim przypadku niegrupowania sektorów

Potrzeba mi testów, nie mam sprzętu pod ręką.

**Comment by Jaom** [comment]
Trochę ten merge pending już wisi...

**Comment by emkael** [comment]
Wczoraj przetestowałem, za jednocyfrową liczbę godzin będzie release w emkael/aktywator.
Tzn. teraz już tam jest, ale delikatnie błędny.

**Comment by emkael** [comment]
https://github.com/emkael/aktywator/releases/tag/v1.1.5-rc
