### ISSUE TITLE
Bezpieczeństwo PINów

### ISSUE THREAD

**Issue by emkael** [michzimny/aktywator#48]
Propozycja ulepszenia bezpieczeństwa PINów:
 - przy inicjalizacji BWSa dotychczas ustawiany był domyślny PIN - może być ustawiany losowy
 - losowy PIN powinno ustawiać się łatwo, bez potrzeby mentalnej symulacji PRNG
 - łatwo przewidywalne PINy (np. dotychczasowy domyślny) powinny wywoływać w użytkowniku poczucie wstydu
 - nie powinniśmy pozwalać na obecność w BWSie rozkładów przy takich PINach

![random-pin](https://user-images.githubusercontent.com/3368944/47377657-6b3fd380-d6e5-11e8-96c2-bf1cc1c60442.gif)

**Comment by michzimny** [comment]
Super.
Jakie piny są przewidywalne? Chyba dotychczasowy domyślny też powinien być takim.

**Comment by emkael** [comment]
> Jakie piny są przewidywalne? Chyba dotychczasowy domyślny też powinien być takim.

Tak, jest.

Listy PINów przewidywalnych z przyczyn oczywistych nie chciałbym publikować w postaci łatwo przyswajalnej - proponuję, żebyś podejrzał sobie w kodzie: https://github.com/emkael/aktywator/blob/e37fd194f74a7548b1fe9d7866cea2b2b64e5504/Aktywator/Bws.cs#L419 :)

Jeśli masz jeszcze jakieś propozycje przewidywalnych PINów, śmiało.
