### ISSUE TITLE
Wsparcie teamów

### ISSUE THREAD

**Issue by Jaom** [michzimny/aktywator#51]
> Version:		3.0.1
Date:			February 13th, 2018
Requires server:	3.0.1d USB	usbs301d.exe
File name:		BM2_3-0-1.BM2
`Team games functionality added. Teams can review scores from both matches and view their match results in IMP at the end of the match.`

**Comment by emkael** [comment]
Jeśli okaże się wystarczająco niewielkie (np. kwestia jednej flagi), to pewnie zmieści się jeszcze w 1.1.5.

**Comment by emkael** [comment]
Jesteś pewien, że to funkcjonalność BWSów, a nie tylko BCS (jak np. ustawienia liczenia butlera/cavendisha czy listing wezwań sędziowskich)?
Devguide milczy na ten temat, a cały rozdział "Team games" jest zaimplementowany (poza tematami ustawień do kolejnych rund, bo Teamów nie dotyczą) - i skutkuje jedynie pokazaniem wyniku pojedynczego rozdania w IMPach.
Nie widzę żadnych flag, nie widzę nic nawet w historii wersji devguide'a.

**Comment by Jaom** [comment]
Prawdę mówiąc nie wiem - ogólnie zgubiłem się w którymś momencie w tym co jest u Ciebie zaimplementowane i tym co leży u Zimnego i tym co wprowadził Bridgemate.

Jeśli z pomocą Aktywatora da się uzyskac końcowy rezultat taki jak na screenach poniżej (znasz je to będziesz wiedział), to pewnie wszystko już jest zaimplementowane:
![41619241_666211373764719_2018556005448679424_n](https://user-images.githubusercontent.com/2835003/48662622-e1d1b600-ea84-11e8-9745-03bf719fda97.png)
![41667449_309753679811036_448929747217416192_n](https://user-images.githubusercontent.com/2835003/48662623-e1d1b600-ea84-11e8-9591-d541ca2429be.png)

**Comment by emkael** [comment]
W manualu jest tyle:
![image](https://user-images.githubusercontent.com/3368944/48663983-d041db80-ea8f-11e8-9a85-7e69d61e6f20.png)

To by znaczyło, że ustawienie ScoringType na teamowy (4) i włączenie podsumowania na koniec rundy powinno to wyświetlić.
Sprawdzę wieczorem.

**Comment by emkael** [comment]
Takie samo podsumowanie dostępne jest też dla turniejów par (i działa z maksami, cavendishem i butlerem), po podaniu numeru pary na koniec sesji.
