### ISSUE TITLE
Nie pyta o ID :(

### ISSUE THREAD

**Issue by Jaom** [michzimny/aktywator#9]
Jak się wgra nazwiska i zaznaczy, że ma pytać o id i nie może pytać o id, to nie pyta o id.
Innymi słowy w teamach efekt jest odmienny od oczekiwanego.

Testowałem niestety tylko w boju i przypadkiem. Zdarzyło mi się dwa razy, gdzie jeden teraz na najnowszym sofcie i firmware, wcześniejszy "test" był, mam wrażenie, ze 2-3 lata temu.

**Comment by emkael** [comment]
> zaznaczy, że ma pytać o id i nie może pytać o id, to nie pyta o id

Myślałem, że jak odłożę to zdanie do szuflady na miesiąc, to za drugim razem je zrozumiem, ale jednak nie.

Skoro nie może pytać o ID, to czemu miałoby... pytać o ID?

**Comment by Jaom** [comment]
Też nie wiem co miałem w tamtym zdaniu na myśli. :(

Na pewno był taki case:
- wczytuję "nazwiska" z teamów
- zaznaczam "pokazuj nazwiska"
- zaznaczam "podaj ID" i "ID nie może być puste"

BM2 nie pyta o nazwiska. Może dlatego, że myśli, że już ma? (w końcu coś mu wgrałem w tabelę z nazwiskami).

**Comment by emkael** [comment]
Artur coś też miał z wyświetlaniem nazw teamów, jak III ligę robiliśmy, ale to się chyba powinno objawiać w drugą stronę - niewyświetlaniem nazw teamów.

Bo dotychczas (przed 1.1.0-beta) jak `PlayerNumbers` było puste (a w przypadku Teamów przeważnie jest), to do BWSa nie zapisywały się nazwiska, bo zapisywanie było robione przez `UPDATE` na `PlayerNumbers`. Beta 1.1.0 wstawia brakujące wiersze do `PlayerNumbers`, nie wypełniając przy tym numerów.

Gdyby występowało to, co podejrzewasz (serwer widzi wiersz, więc nie pyta o ID), to z kolei zapomnienie odznaczenia "pytaj o numery" nie byłoby tak upierdliwe przy recoverze serwera z BWSa - bo przecież wtedy są wpisy w `PlayerNumbers`, nawet z numerami, ale i tak pyta (choć w innej rundzie).

**Comment by Jaom** [comment]
A właśnie! W Montecatini recovery serwera nie zapytał o ID zawodników! A ja celowo zwróciłem uwagę, że to przed recovery trzeba wyłączyć.
Może to nie bug tylko feature w postaci zmiany zachowania? Zwłaszcza jeśli dopuścić, że to tylko z BM2 ma miejsce.  Peter Eidit mówił, że BM2 przy recovery nigdy nie pytają co wydało mi się dziwne. Może długo w Polsce używaliśmy jakiejś wersji BMC / firmware na BM2, co powodowało odmienne zachowanie?

**Comment by emkael** [comment]
Jedyne, co widzę, to zmiany w wersji 2.2.1 - tej, która wprowadzała również sprawdzenie karty wistu, więc tej, którą w praktyce zaczęliśmy w PL używać w listopadzie 2016 (choć wersja jest z marca 2016):

- Option added to enter player numbers at each round.
- Player names can be reviewed from the score entry screen and modified.

Ta druga opcja pewnie dotyczy trybu, w którym nazwiska są trzymane w `PlayerNames`, a nie w `PlayerNumbers`, ale musiałbym się upewnić. Gdyby dało radę jakoś powiadamiać "ej, zawodnik poprawił swoje nazwisko w pierniczku", to może i przydatna opcja by była.

A ten pierwszy punkt mocno sugeruje, że skoro pytanie w każdej rundzie jest *opcjonalne*, to coś tu może być nie tak. Poszukam w dokumentacji.

**Comment by Jaom** [comment]
Podnosi mnie na duchu Twoja wiara w ich dokumentację.
Podobno z owej dokumentacji wynika, że im niższy kanał tym większy zasięg pierniczków. Co jest ciekawe, bo ponoć w puli pierniczki działają w jednej sali wyłącznie na kanale siódmym (ale może to kwestia zakłóceń).

**Comment by emkael** [comment]
In my world, shit may not necessarily get done, but shit as sure as hell gets documented.

**Comment by emkael** [comment]
Tak, jak podejrzewałem - od wersji BCS 3.2.1 (firmware 2.2.1 - tej samej, która wprowadzała weryfikację karty pierwszego wyjścia) wprowadzono nową logikę wpisywania numerów zawodników.  
Możliwe jest wpisanie numerów na początku każdej rundy, a do tego do pierniczka ładowane są numery, które już są wpisane (np. przez program liczący).

W naszym przypadku jedyna opcja wyświetlania nazw(isk) to użycie tabeli `PlayerNumbers`, bo to jedyne miejsce wiążące pozycję startową z nazwą, bez użycia numerów uczestników - a w takim przypadku, gdy nazwa jest już obecna, pierniczek nie pyta o numer.

Ale. Można włączyć wprowadzoną wówczas opcję `BM2NumberEntryEachRound`. Pierniczek pyta wtedy o numery zawodników zawsze (przed każdą rundą - oczywiście do włączenia tylko w przypadku teamów).  
Do tego opcja `BM2NumberEntryPreloadValues` powoduje, że pierniczek pyta nie tylko o brakujące numery, ale o wszystkie, ładując istniejące do poprawki (w naszym wypadku - bez niej pobierane byłyby tylko numery S i W, a tak - ładowane są domyślne zera/nulle obecne w `PlayerNumbers`, więc pierniczek pyta o wszystkie cztery numery).

Niestety, pyta o nie **przed** wyświetleniem informacji rundy. Proces wygląda tak:
  * [pierniczek pyta o numery uczestników](https://user-images.githubusercontent.com/3368944/29563183-c29829e2-873c-11e7-90ad-8fbdb14f1a54.jpg)
  * [pierniczek po komunikacji z serwerem wyświetla nazwy powiązane z numerami (w naszym przypadku: wyświetli nazwy teamów) i pyta o ich potwierdzenie](https://user-images.githubusercontent.com/3368944/29563184-c2af9654-873c-11e7-8ed9-6559816b8a8b.jpg) (normalnie byłoby to używane do powiązania dopiero co wprowadzonego numeru z nazwiskiem i wyświetlenia nazwiska, gdybyśmy używali innego trybu wprowadzania nazwisk)
  * pierniczek wyświetla normalne informacje o rundzie - [najpierw ekran z numerami rozdań](https://user-images.githubusercontent.com/3368944/29563185-c2b3d1a6-873c-11e7-866c-9f81e3cd3396.jpg), [następnie ekran z nazwami teamów](https://user-images.githubusercontent.com/3368944/29563182-c2964ab4-873c-11e7-9b21-88f02bfa93eb.jpg)

Jeśli taki proces jest akceptowalny, dopiszę do modułu czytania nazwisk z JFR Teamy ustawianie w/w opcji. Cały proces wygląda identycznie nawet przy starożytnej wersji firmware 2.1.1.  
Jeśli nie, to potrzebuję jakiejś pomocy ze strony BridgeMate (np. opcji przywracającej "stary" proces).

Przykładowy plik BWS dla Teamów: [test-1.zip](https://github.com/michzimny/aktywator/files/1241776/test-1.zip)

**Comment by michzimny** [comment]
Chyba chcemy, żeby się wyświetlały nazwy teamów, tak? Więc jeśli opisany przez Ciebie proces nie byłby akceptowalny, to jaka byłaby alternatywa?

**Comment by emkael** [comment]
Napisanie do BM, pokazanie specyficznego przypadku użycia, w którym jednocześnie w `PlayersNumbers` znajdują się wypełnione nazwy, jak i jest potrzeba pytania o wszystkie ID i prośba o implementację opcji, która to wymusi inaczej niż ustawianie `BM2NumberEntryEachRound` i `BM2NumberEntryPreloadValues`.

W ogóle - ktoś pamięta, czy przed tym, jak się popsuło, ID były w ogóle czytane *po* wyświetlaniu nazw teamów? Może zawsze były czytane przed, więc teraz dodatkowo mamy możliwość sprawdzenia na ekranie nazw teamów na właściwych liniach, zanim cokolwiek wypełnimy (w tym: lineup).

**Comment by emkael** [comment]
Zrobione w: https://github.com/emkael/aktywator/releases/tag/v1.1.1-beta

**Comment by Jaom** [comment]
Wydaje mi się, że numerki chcemy czytać niemal zawsze, bo do butlera, a mimo prób nie udało się zaimplementować sensownie sytemu line-upów jak w EBL/WBF (tam jest interface webowy via Internet wiec to ma więcej sensu, bo każdy z telefonu może wyklikać, podobnie jak automatyczne kary za late laneup wspomagają proces).

Ponadto uważam, że nadzieja, że ktoś zorientuje się, że siedzi na złej linii na tej podstawie że zerknie w pierniczka i zobaczy nazwy jest skrajnie iluzoryczna. W moim odczuciu pokazywanie nazw teamów w pierniczku to zwyczajny wodotrysk.

Aktualnie nie jestem pewny na jakim rozwiązaniu stanęło, a opis "poprawiono błąd pobierania numerów graczy przy wyświetlonych nazwach teamów" w release nie pozwala mi się domyślić. :)

**Comment by emkael** [comment]
A ja nie jestem pewny, jakie rozwiązanie proponuje Twój komentarz.

Aktualnie stanęło na rozwiązaniu opisywanym i obfotografowanym powyżej. Jest to jedyne rozwiązanie, które znalazłem, a które pozwala jednocześnie pobrać ID i wyświetlić nazwy teamów. Dotyczy ono tylko importu nazw z Teamów (w sumie w przyszłym tygodniu, gdy będę mieć znowu dostęp do sprzętu, przetestuję dokładniej, czy nic nie zepsuło się w turniejach par), i wprowadza dodatkowy ekran potwierdzenia, który w teamach może być odrobinę mylący (komunikat "Cancel żeby poprawić" nie poprawi tego, co na tym ekranie widzą gracze, bo na tym ekranie nie są wyświetlane dane wprowadzone wcześniej).

Co do wodotryskowości - zwracam uwagę, że oprócz nazw teamów dysponujemy na tym ekranie jedną wolną linią per team. Może ona służyć np. do komunikowania kar za spóźnienie albo wyświetlania bieżącego wyniku w meczach o wielu segmentach.
